server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shuto4ka/k8s-deployment.git
          search-paths: configs/link-aggregator
#          uri: /home/aleksandr/projects/configs/link-aggregator
#          search-paths: subdir

management.endpoints.web.exposure.include: ["health", "info"]